export const decorationColorVariants = {
  amber: "decoration-amber-9",
  blue: "decoration-blue-9",
  bronze: "decoration-bronze-9",
  brown: "decoration-brown-9",
  crimson: "decoration-crimson-9",
  cyan: "decoration-cyan-9",
  gold: "decoration-gold-9",
  grass: "decoration-grass-9",
  green: "decoration-green-9",
  indigo: "decoration-indigo-9",
  lime: "decoration-lime-9",
  mint: "decoration-mint-9",
  orange: "decoration-orange-9",
  pink: "decoration-pink-9",
  plum: "decoration-plum-9",
  purple: "decoration-purple-9",
  red: "decoration-red-9",
  sky: "decoration-sky-9",
  teal: "decoration-teal-9",
  tomato: "decoration-tomato-9",
  violet: "decoration-violet-9",
  yellow: "decoration-yellow-9",
};
