import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "%s • Miguel Rocha",
    default: "Miguel Rocha",
  },
  description: "This is Miguel Rocha's website, an amazing software developer!",
  applicationName: "Miguel Rocha's Website",
  referrer: "origin-when-cross-origin",
  colorScheme: "light",
  generator: "NextJS",
  category: "technology",
  keywords: [
    "Website",
    "Personal website",
    "Miguel Rocha",
    "Miguel",
    "Rocha",
    "Technology",
    "Software developer",
    "Developer",
    "Full-stack developer",
    "Portfolio",
    "NextJS",
    "React",
    "TypeScript",
    "JavaScript",
    "TailwindCSS",
    "PostCSS",
    "Radix UI",
    "Server components",
    "Client components",
    "Server functions",
    "App directory",
  ],
  creator: "Miguel Rocha <https://www.miguelrocha.dev/>",
  publisher: "Miguel Rocha <https://www.miguelrocha.dev/>",
  authors: [{ name: "Miguel Rocha", url: "https://www.miguelrocha.dev/" }],
};
